package com.yourname.habitapp.utils

import com.yourname.habitapp.data.models.HabitCategory

data class HabitSuggestion(
    val name: String,
    val icon: String,
    val category: HabitCategory
)

object HabitTemplates {
    val CATEGORY_NAMES = mapOf(
        HabitCategory.HEALTH to "الصحة",
        HabitCategory.FITNESS to "اللياقة البدنية",
        HabitCategory.PRODUCTIVITY to "الإنتاجية والعمل",
        HabitCategory.LEARNING to "التعلم والتطوير",
        HabitCategory.SPIRITUAL to "الجانب الروحاني",
        HabitCategory.SOCIAL to "العلاقات الاجتماعية",
        HabitCategory.FINANCE to "المالية",
        HabitCategory.HOBBY to "الهوايات",
        HabitCategory.HOME to "المنزل",
        HabitCategory.SELF_IMPROVEMENT to "تطوير الذات",
        HabitCategory.OTHER to "أخرى"
    )

    val ALL_SUGGESTIONS = listOf(
        // --- HEALTH (20) ---
        HabitSuggestion("شرب الماء (8 أكواب)", "💧", HabitCategory.HEALTH),
        HabitSuggestion("نوم مبكر", "😴", HabitCategory.HEALTH),
        HabitSuggestion("أكل فاكهة", "🍎", HabitCategory.HEALTH),
        HabitSuggestion("تقليل السكر", "🚫", HabitCategory.HEALTH),
        HabitSuggestion("فطور صحي", "🥣", HabitCategory.HEALTH),
        HabitSuggestion("غسل الأسنان", "🪥", HabitCategory.HEALTH),
        HabitSuggestion("خيط الأسنان", "🦷", HabitCategory.HEALTH),
        HabitSuggestion("شاي أخضر", "🍵", HabitCategory.HEALTH),
        HabitSuggestion("تجنب الأكل الجاهز", "🍔", HabitCategory.HEALTH),
        HabitSuggestion("فيتامينات", "💊", HabitCategory.HEALTH),
        HabitSuggestion("تقليل الكافيين", "☕", HabitCategory.HEALTH),
        HabitSuggestion("أكل خضروات", "🥦", HabitCategory.HEALTH),
        HabitSuggestion("ماء بالليمون", "🍋", HabitCategory.HEALTH),
        HabitSuggestion("لا شاشات قبل النوم", "📱", HabitCategory.HEALTH),
        HabitSuggestion("قيلولة قصيرة", "💤", HabitCategory.HEALTH),
        HabitSuggestion("جلسة صحيحة", "🪑", HabitCategory.HEALTH),
        HabitSuggestion("مضغ الطعام جيداً", "👄", HabitCategory.HEALTH),
        HabitSuggestion("الاستيقاظ بدون منبه", "☀️", HabitCategory.HEALTH),
        HabitSuggestion("ماء فور الاستيقاظ", "🥛", HabitCategory.HEALTH),
        HabitSuggestion("حمام بارد", "🚿", HabitCategory.HEALTH),

        // --- FITNESS (20) ---
        HabitSuggestion("مشي 30 دقيقة", "🚶", HabitCategory.FITNESS),
        HabitSuggestion("تمارين ضغط", "💪", HabitCategory.FITNESS),
        HabitSuggestion("النادي الرياضي", "🏋️", HabitCategory.FITNESS),
        HabitSuggestion("إحماء صباحي", "🤸", HabitCategory.FITNESS),
        HabitSuggestion("ركوب الدراجة", "🚴", HabitCategory.FITNESS),
        HabitSuggestion("يوغا", "🧘", HabitCategory.FITNESS),
        HabitSuggestion("بلانك (دقيقة)", "⏱️", HabitCategory.FITNESS),
        HabitSuggestion("استخدام الدرج", "🪜", HabitCategory.FITNESS),
        HabitSuggestion("جري 2 كم", "🏃", HabitCategory.FITNESS),
        HabitSuggestion("تمارين بطن", "🤸", HabitCategory.FITNESS),
        HabitSuggestion("سباحة", "🏊", HabitCategory.FITNESS),
        HabitSuggestion("تمدد", "🧘‍♀️", HabitCategory.FITNESS),
        HabitSuggestion("10,000 خطوة", "🐾", HabitCategory.FITNESS),
        HabitSuggestion("كرة قدم", "⚽", HabitCategory.FITNESS),
        HabitSuggestion("تمارين أوزان", "🏋️‍♀️", HabitCategory.FITNESS),
        HabitSuggestion("تجنب الجلوس الطويل", "🚶‍♂️", HabitCategory.FITNESS),
        HabitSuggestion("رياضة قتالية", "🥋", HabitCategory.FITNESS),
        HabitSuggestion("قرفصاء", "🍑", HabitCategory.FITNESS),
        HabitSuggestion("تمارين عقلة", "🧗", HabitCategory.FITNESS),
        HabitSuggestion("قفز الحبل", "🪢", HabitCategory.FITNESS),

        // --- PRODUCTIVITY (20) ---
        HabitSuggestion("تخطيط الغد", "📝", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("تنظيف الإيميل", "📧", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("مراجعة الأهداف", "🎯", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("تركيز (60د)", "⌛", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("قراءة إيميلات العمل", "💻", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("قاعدة الـ 5 دقائق", "🖐️", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("ترتيب المكتب", "🖥️", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("المهمة الصعبة أولاً", "🐸", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("بومودورو", "🍅", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("قائمة المهام", "📋", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("تجهيز ملابس الغد", "👔", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("مراجعة النفقات", "💸", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("تقليل السوشيال ميديا", "📵", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("فترات راحة", "☕", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("سجل الإنجازات", "🏆", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("الرد على الرسائل", "💬", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("حذف تطبيقات", "🗑️", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("تسجيل الأفكار", "💡", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("متابعة التقويم", "📅", HabitCategory.PRODUCTIVITY),
        HabitSuggestion("لا تعدد مهام", "🧠", HabitCategory.PRODUCTIVITY),

        // --- LEARNING (20) ---
        HabitSuggestion("قراءة 10 صفحات", "📖", HabitCategory.LEARNING),
        HabitSuggestion("تعلم 5 كلمات", "🌍", HabitCategory.LEARNING),
        HabitSuggestion("متابعة كورس", "🎓", HabitCategory.LEARNING),
        HabitSuggestion("حل مسألة برمجية", "🧩", HabitCategory.LEARNING),
        HabitSuggestion("مشاهدة TED", "📺", HabitCategory.LEARNING),
        HabitSuggestion("بودكاست مفيد", "🎧", HabitCategory.LEARNING),
        HabitSuggestion("مهارة يدوية", "🛠️", HabitCategory.LEARNING),
        HabitSuggestion("كتابة ملخص", "✍️", HabitCategory.LEARNING),
        HabitSuggestion("بحث عن موضوع", "🔍", HabitCategory.LEARNING),
        HabitSuggestion("قراءة مقال", "🔬", HabitCategory.LEARNING),
        HabitSuggestion("عزف آلة", "🎸", HabitCategory.LEARNING),
        HabitSuggestion("تحسين الكتابة", "⌨️", HabitCategory.LEARNING),
        HabitSuggestion("أخبار التكنولوجيا", "🤖", HabitCategory.LEARNING),
        HabitSuggestion("مهارة طبخ", "👨‍🍳", HabitCategory.LEARNING),
        HabitSuggestion("مراجعة دروس", "📚", HabitCategory.LEARNING),
        HabitSuggestion("ورشة عمل", "🤝", HabitCategory.LEARNING),
        HabitSuggestion("لغة برمجة", "💻", HabitCategory.LEARNING),
        HabitSuggestion("حفظ مقولة", "💭", HabitCategory.LEARNING),
        HabitSuggestion("مشاهدة وثائقي", "📽️", HabitCategory.LEARNING),
        HabitSuggestion("إسعافات أولية", "🩹", HabitCategory.LEARNING),

        // --- SPIRITUAL (20) ---
        HabitSuggestion("الصلاة في وقتها", "🕌", HabitCategory.SPIRITUAL),
        HabitSuggestion("ورد القرآن", "📖", HabitCategory.SPIRITUAL),
        HabitSuggestion("أذكار الصباح", "🌅", HabitCategory.SPIRITUAL),
        HabitSuggestion("أذكار المساء", "🌃", HabitCategory.SPIRITUAL),
        HabitSuggestion("صدقة يومية", "🤲", HabitCategory.SPIRITUAL),
        HabitSuggestion("استغفار (100)", "✨", HabitCategory.SPIRITUAL),
        HabitSuggestion("صلاة الضحى", "☀️", HabitCategory.SPIRITUAL),
        HabitSuggestion("صلاة الوتر", "🌙", HabitCategory.SPIRITUAL),
        HabitSuggestion("دعاء للغير", "💖", HabitCategory.SPIRITUAL),
        HabitSuggestion("قراءة حديث", "📜", HabitCategory.SPIRITUAL),
        HabitSuggestion("تدبر آية", "🧐", HabitCategory.SPIRITUAL),
        HabitSuggestion("زيارة المسجد", "🕌", HabitCategory.SPIRITUAL),
        HabitSuggestion("قيام الليل", "🕯️", HabitCategory.SPIRITUAL),
        HabitSuggestion("صيام تطوعي", "🥛", HabitCategory.SPIRITUAL),
        HabitSuggestion("شكر النعم", "🙏", HabitCategory.SPIRITUAL),
        HabitSuggestion("بر الوالدين", "👵", HabitCategory.SPIRITUAL),
        HabitSuggestion("ترك الغيبة", "🤐", HabitCategory.SPIRITUAL),
        HabitSuggestion("كتاب ديني", "📔", HabitCategory.SPIRITUAL),
        HabitSuggestion("درس ديني", "🔊", HabitCategory.SPIRITUAL),
        HabitSuggestion("صلة الرحم", "☎️", HabitCategory.SPIRITUAL),

        // --- SOCIAL (20) ---
        HabitSuggestion("اتصال بالعائلة", "📞", HabitCategory.SOCIAL),
        HabitSuggestion("مقابلة صديق", "☕", HabitCategory.SOCIAL),
        HabitSuggestion("مساعدة غريب", "🤝", HabitCategory.SOCIAL),
        HabitSuggestion("رسالة شكر", "💌", HabitCategory.SOCIAL),
        HabitSuggestion("وقت مع الأبناء", "👨‍👩‍👧", HabitCategory.SOCIAL),
        HabitSuggestion("ابتسامة", "😊", HabitCategory.SOCIAL),
        HabitSuggestion("عمل تطوعي", "🌍", HabitCategory.SOCIAL),
        HabitSuggestion("هدية بسيطة", "🎁", HabitCategory.SOCIAL),
        HabitSuggestion("عشاء عائلي", "🍽️", HabitCategory.SOCIAL),
        HabitSuggestion("استماع جيد", "👂", HabitCategory.SOCIAL),
        HabitSuggestion("لا هاتف مع الناس", "📵", HabitCategory.SOCIAL),
        HabitSuggestion("إفشاء السلام", "✋", HabitCategory.SOCIAL),
        HabitSuggestion("مدح الآخرين", "👏", HabitCategory.SOCIAL),
        HabitSuggestion("مناسبة اجتماعية", "🎉", HabitCategory.SOCIAL),
        HabitSuggestion("رسالة خطية", "✍️", HabitCategory.SOCIAL),
        HabitSuggestion("اعتذار", "🙏", HabitCategory.SOCIAL),
        HabitSuggestion("نزهة جماعية", "🧺", HabitCategory.SOCIAL),
        HabitSuggestion("دعم محلي", "🏪", HabitCategory.SOCIAL),
        HabitSuggestion("وجبة لجار", "🍲", HabitCategory.SOCIAL),
        HabitSuggestion("تواصل مع معلم", "👨‍🏫", HabitCategory.SOCIAL),

        // --- FINANCE (20) ---
        HabitSuggestion("تسجيل المصاريف", "💰", HabitCategory.FINANCE),
        HabitSuggestion("توفير 10%", "🏦", HabitCategory.FINANCE),
        HabitSuggestion("ميزانية شهرية", "📊", HabitCategory.FINANCE),
        HabitSuggestion("فرص استثمار", "📈", HabitCategory.FINANCE),
        HabitSuggestion("ثقافة مالية", "🗞️", HabitCategory.FINANCE),
        HabitSuggestion("لا شراء اندفاعي", "🛒", HabitCategory.FINANCE),
        HabitSuggestion("دفع الفواتير", "📑", HabitCategory.FINANCE),
        HabitSuggestion("استخدام النقد", "💵", HabitCategory.FINANCE),
        HabitSuggestion("مراجعة اشتراكات", "📉", HabitCategory.FINANCE),
        HabitSuggestion("قائمة تسوق", "📝", HabitCategory.FINANCE),
        HabitSuggestion("كود خصم", "🏷️", HabitCategory.FINANCE),
        HabitSuggestion("مبلغ طوارئ", "🚨", HabitCategory.FINANCE),
        HabitSuggestion("مقارنة أسعار", "🧐", HabitCategory.FINANCE),
        HabitSuggestion("بيع المستعمل", "♻️", HabitCategory.FINANCE),
        HabitSuggestion("صافي الثروة", "💎", HabitCategory.FINANCE),
        HabitSuggestion("سقف يومي", "🚧", HabitCategory.FINANCE),
        HabitSuggestion("الأب الغني", "📘", HabitCategory.FINANCE),
        HabitSuggestion("غداء منزلي", " Sandwich ", HabitCategory.FINANCE),
        HabitSuggestion("فهم الضرائب", "🧾", HabitCategory.FINANCE),
        HabitSuggestion("دخل إضافي", "🚀", HabitCategory.FINANCE),

        // --- HOBBY (20) ---
        HabitSuggestion("رسم", "🎨", HabitCategory.HOBBY),
        HabitSuggestion("عزف", "🎸", HabitCategory.HOBBY),
        HabitSuggestion("طبخ طبق جديد", "🍳", HabitCategory.HOBBY),
        HabitSuggestion("تصوير", "📷", HabitCategory.HOBBY),
        HabitSuggestion("كتابة إبداعية", "✍️", HabitCategory.HOBBY),
        HabitSuggestion("ألعاب فيديو", "🎮", HabitCategory.HOBBY),
        HabitSuggestion("عناية بالحديقة", "🌻", HabitCategory.HOBBY),
        HabitSuggestion("خياطة", "🧵", HabitCategory.HOBBY),
        HabitSuggestion("تجميع طوابع", "🏷️", HabitCategory.HOBBY),
        HabitSuggestion("مشغولات يدوية", "🧶", HabitCategory.HOBBY),
        HabitSuggestion("كلمات متقاطعة", "✏️", HabitCategory.HOBBY),
        HabitSuggestion("خدع بصرية", "🪄", HabitCategory.HOBBY),
        HabitSuggestion("متابعة رياضة", "🏀", HabitCategory.HOBBY),
        HabitSuggestion("برمجة تطبيق", "⌨️", HabitCategory.HOBBY),
        HabitSuggestion("تلوين", "🖍️", HabitCategory.HOBBY),
        HabitSuggestion("محتوى فيديو", "🎬", HabitCategory.HOBBY),
        HabitSuggestion("تمثيل", "🎭", HabitCategory.HOBBY),
        HabitSuggestion("نادي كتاب", "📚", HabitCategory.HOBBY),
        HabitSuggestion("مراقبة نجوم", "🔭", HabitCategory.HOBBY),
        HabitSuggestion("البومات صور", "📔", HabitCategory.HOBBY),

        // --- HOME (20) ---
        HabitSuggestion("ترتيب السرير", "🧹", HabitCategory.HOME),
        HabitSuggestion("سقي النباتات", "🪴", HabitCategory.HOME),
        HabitSuggestion("تنظيف المطبخ", "🧼", HabitCategory.HOME),
        HabitSuggestion("تخلص من 3 أشياء", "📦", HabitCategory.HOME),
        HabitSuggestion("غسل الملابس", "🧺", HabitCategory.HOME),
        HabitSuggestion("مسح الغبار", "✨", HabitCategory.HOME),
        HabitSuggestion("تنظيم الخزانة", "👗", HabitCategory.HOME),
        HabitSuggestion("رمي النفايات", "🗑️", HabitCategory.HOME),
        HabitSuggestion("ديكور بسيط", "🖼️", HabitCategory.HOME),
        HabitSuggestion("فحص صلاحية", "🧊", HabitCategory.HOME),
        HabitSuggestion("تلميع الزجاج", "🪞", HabitCategory.HOME),
        HabitSuggestion("تعطير المنزل", "🕯️", HabitCategory.HOME),
        HabitSuggestion("ترتيب الأحذية", "👟", HabitCategory.HOME),
        HabitSuggestion("تنظيف الثلاجة", "🥦", HabitCategory.HOME),
        HabitSuggestion("مستلزمات المنزل", "🛒", HabitCategory.HOME),
        HabitSuggestion("غسل الصحون", "🍽️", HabitCategory.HOME),
        HabitSuggestion("كنس الأرضية", "🧹", HabitCategory.HOME),
        HabitSuggestion("تهوية المنزل", "🪟", HabitCategory.HOME),
        HabitSuggestion("تنظيف الحمام", "🚽", HabitCategory.HOME),
        HabitSuggestion("إصلاح شيء", "🔨", HabitCategory.HOME),

        // --- SELF_IMPROVEMENT (20) ---
        HabitSuggestion("يوميات", "📓", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("تأمل", "🧘", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("تنفس عميق", "🌬️", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("صمت", "🤫", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("امتنان (3 أشياء)", "🙏", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("تحدث إيجابي", "🗣️", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("مواجهة خوف", "🦁", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("قول لا", "🚫", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("هدف جديد", "🎯", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("استيقاظ مبكر", "🌅", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("وقت في الطبيعة", "🌳", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("تحدي النفس", "🔥", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("مراجعة عادات سيئة", "🛑", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("استماع للذات", "🧠", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("لا مقارنة", "🧘‍♂️", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("مظهر شخصي", "🤵", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("تنظيم النوم", "🕒", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("حمام بارد", "❄️", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("توكيدات", "🗣️", HabitCategory.SELF_IMPROVEMENT),
        HabitSuggestion("سلام داخلي", "🕊️", HabitCategory.SELF_IMPROVEMENT)
    )
}
